/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.unicorn.kafka;
@SuppressWarnings("all")
/** Types of Events */
@org.apache.avro.specific.AvroGenerated
public enum EventType {
  NEW_MESSAGE, DUPLICATED_MESSAGE, READY_FOR_PROCESSING, VALIDATION_REPORT, UNRECOGNIZED_MESSAGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"eu.unicorn.kafka\",\"doc\":\"Types of Events\",\"symbols\":[\"NEW_MESSAGE\",\"DUPLICATED_MESSAGE\",\"READY_FOR_PROCESSING\",\"VALIDATION_REPORT\",\"UNRECOGNIZED_MESSAGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
