/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.unicorn.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2058234675324423271L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"eu.unicorn.kafka.avro\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"receivedFile\",\"type\":\"string\"},{\"name\":\"topicOffset\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Event> ENCODER =
      new BinaryMessageEncoder<Event>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Event> DECODER =
      new BinaryMessageDecoder<Event>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Event> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Event> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Event>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Event to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Event from a ByteBuffer. */
  public static Event fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.lang.CharSequence receivedFile;
  @Deprecated public long topicOffset;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Event() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param receivedFile The new value for receivedFile
   * @param topicOffset The new value for topicOffset
   */
  public Event(java.lang.CharSequence type, java.lang.CharSequence receivedFile, java.lang.Long topicOffset) {
    this.type = type;
    this.receivedFile = receivedFile;
    this.topicOffset = topicOffset;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return receivedFile;
    case 2: return topicOffset;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.CharSequence)value$; break;
    case 1: receivedFile = (java.lang.CharSequence)value$; break;
    case 2: topicOffset = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'receivedFile' field.
   * @return The value of the 'receivedFile' field.
   */
  public java.lang.CharSequence getReceivedFile() {
    return receivedFile;
  }

  /**
   * Sets the value of the 'receivedFile' field.
   * @param value the value to set.
   */
  public void setReceivedFile(java.lang.CharSequence value) {
    this.receivedFile = value;
  }

  /**
   * Gets the value of the 'topicOffset' field.
   * @return The value of the 'topicOffset' field.
   */
  public java.lang.Long getTopicOffset() {
    return topicOffset;
  }

  /**
   * Sets the value of the 'topicOffset' field.
   * @param value the value to set.
   */
  public void setTopicOffset(java.lang.Long value) {
    this.topicOffset = value;
  }

  /**
   * Creates a new Event RecordBuilder.
   * @return A new Event RecordBuilder
   */
  public static eu.unicorn.kafka.avro.Event.Builder newBuilder() {
    return new eu.unicorn.kafka.avro.Event.Builder();
  }

  /**
   * Creates a new Event RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Event RecordBuilder
   */
  public static eu.unicorn.kafka.avro.Event.Builder newBuilder(eu.unicorn.kafka.avro.Event.Builder other) {
    return new eu.unicorn.kafka.avro.Event.Builder(other);
  }

  /**
   * Creates a new Event RecordBuilder by copying an existing Event instance.
   * @param other The existing instance to copy.
   * @return A new Event RecordBuilder
   */
  public static eu.unicorn.kafka.avro.Event.Builder newBuilder(eu.unicorn.kafka.avro.Event other) {
    return new eu.unicorn.kafka.avro.Event.Builder(other);
  }

  /**
   * RecordBuilder for Event instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
    implements org.apache.avro.data.RecordBuilder<Event> {

    private java.lang.CharSequence type;
    private java.lang.CharSequence receivedFile;
    private long topicOffset;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.unicorn.kafka.avro.Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.receivedFile)) {
        this.receivedFile = data().deepCopy(fields()[1].schema(), other.receivedFile);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.topicOffset)) {
        this.topicOffset = data().deepCopy(fields()[2].schema(), other.topicOffset);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Event instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.unicorn.kafka.avro.Event other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.receivedFile)) {
        this.receivedFile = data().deepCopy(fields()[1].schema(), other.receivedFile);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.topicOffset)) {
        this.topicOffset = data().deepCopy(fields()[2].schema(), other.topicOffset);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public eu.unicorn.kafka.avro.Event.Builder setType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public eu.unicorn.kafka.avro.Event.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'receivedFile' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceivedFile() {
      return receivedFile;
    }

    /**
      * Sets the value of the 'receivedFile' field.
      * @param value The value of 'receivedFile'.
      * @return This builder.
      */
    public eu.unicorn.kafka.avro.Event.Builder setReceivedFile(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.receivedFile = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'receivedFile' field has been set.
      * @return True if the 'receivedFile' field has been set, false otherwise.
      */
    public boolean hasReceivedFile() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'receivedFile' field.
      * @return This builder.
      */
    public eu.unicorn.kafka.avro.Event.Builder clearReceivedFile() {
      receivedFile = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'topicOffset' field.
      * @return The value.
      */
    public java.lang.Long getTopicOffset() {
      return topicOffset;
    }

    /**
      * Sets the value of the 'topicOffset' field.
      * @param value The value of 'topicOffset'.
      * @return This builder.
      */
    public eu.unicorn.kafka.avro.Event.Builder setTopicOffset(long value) {
      validate(fields()[2], value);
      this.topicOffset = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'topicOffset' field has been set.
      * @return True if the 'topicOffset' field has been set, false otherwise.
      */
    public boolean hasTopicOffset() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'topicOffset' field.
      * @return This builder.
      */
    public eu.unicorn.kafka.avro.Event.Builder clearTopicOffset() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Event build() {
      try {
        Event record = new Event();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.receivedFile = fieldSetFlags()[1] ? this.receivedFile : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.topicOffset = fieldSetFlags()[2] ? this.topicOffset : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Event>
    WRITER$ = (org.apache.avro.io.DatumWriter<Event>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Event>
    READER$ = (org.apache.avro.io.DatumReader<Event>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
